routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\PublicController::class, 'index'])->name('home');

Route::get('home', function () {
    return redirect(route('home'));
});

Route::get('login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [\App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login.post');

Route::get('register', [\App\Http\Controllers\Auth\RegisterController::class, 'showRegistrationForm'])->name('register.index');
Route::post('register', [\App\Http\Controllers\Auth\RegisterController::class, 'register'])->name('register.post');

Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::get('search', [\App\Http\Controllers\SearchController::class, 'search'])->name('search');

Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard/user', [\App\Http\Controllers\DashBoardController::class, 'user'])->name('user.dashboard');
    Route::get('dashboard/favorite', [\App\Http\Controllers\DashBoardController::class, 'userFavorite'])->name('user.favorite');

    Route::post('edit-account-info', [\App\Http\MyAccountController::class, 'postAccountInfoForm'])->name('account.info.store');
    Route::post('change-password', [\App\Http\MyAccountController::class, 'postChangePasswordForm'])->name('account.password');

    Route::post('favorite/change/{company_id}', [\App\Http\Controllers\DashBoardController::class, 'changeFavorite'])->name('favorite.change');
});

Route::get('/companies/{company}', [\App\Http\Controllers\CompanyController::class, 'detail'])->name('company.detail');
Route::get('/compare-company/{company_id}', [\App\Http\Controllers\CompanyController::class, 'compareCompany'])->name('company.compare');

app/Models/Company.php
<?php

namespace App\Models;

use Bo\Base\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Company extends Model
{
    use CrudTrait;
    use HasSlug;
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'companies';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];

    public function getImageAttribute()
    {
        if (!$this->image_url) {
            return asset('images/default-images.png');
        }
        return $this->image_url;
    }

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug')
            ->usingLanguage('jp');
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/DashBoardController.php
<?php

namespace App\Http\Controllers;

use App\Models\UserCompanyFavorite;
use Exception;
use Illuminate\Http\Request;

class DashBoardController extends Controller
{
    public function user(Request $request)
    {
        $user = bo_auth()->user();

        return view('dashboard.user', compact('user'));
    }

    public function userFavorite(Request $request)
    {
        $user_favorites = UserCompanyFavorite::where('user_id', bo_user()->getKey())
            ->whereHas('companies', function ($query) {
                return $query->where('status', 'active');
            })
            ->with('companies')
            ->paginate(10);

        return view('dashboard.favorite', compact('user_favorites'));
    }

    public function addFavorite($company_id, Request $request)
    {

    }

    public function changeFavorite($company_id, Request $request)
    {
        try {
            $user_liked = UserCompanyFavorite::where('user_id', bo_user()->getKey())
                ->where('company_id', $company_id);

            $check = $user_liked->exists();

            $user_liked->delete();
            if ($check) {
                //nếu có thì là hành động xóa
                return json_encode([
                    'action' => 'remove'
                ]);
            } else {
                //không có thì thêm vào
                UserCompanyFavorite::create([
                    'user_id'    => bo_user()->getKey(),
                    'company_id' => $company_id
                ]);
                return json_encode([
                    'action' => 'add'
                ]);
            }
        } catch (Exception $exception) {
            return json_encode([
                'action' => 'fail',
                'message' => $exception->getMessage()
            ]);
        }
    }
}

resources/views/dashboard/favorite.blade.php
@extends('dashboard.main')

@section('title', __('Dashboard User Favorite'))

@push('css')
    <style>
        ul.pagination li:last-child a.page-link {
            background-color: #fff !important;
        }

        ul.pagination li:first-child a.page-link {
            background-color: #fff !important;
        }
    </style>
@endpush

@section('main-content')
    @if($user_favorites)
        <div class="container mt-4">
            <div class="text-center mt-2 mb-3">
                <h3>会社一覧</h3>
            </div>
            @foreach ($user_favorites as $user_favorite)
                <div class="card-deck mb-3 text-center">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h5 class="my-0 font-weight-normal">
                                {{$user_favorite->companies->name}} <a href="{{$user_favorite->companies->recruit_url}}">{{$user_favorite->companies->recruit_url}}</a>
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="d-flex justify-content-around">
                                <div class="w-50">
                                    <img class="w-100 border border-primary" src="{{$user_favorite->companies->image}}" alt="{{$user_favorite->companies->name}}">
                                </div>
                                <div>
                                    <h5 class="card-title pricing-card-title">
                                        有効掲載求人数
                                    </h5>
                                    <p>{{$user_favorite->companies->salary}}</p>
                                    <div class="mt-3 mb-4">
                                        <strong>Indeed</strong><span>（{{$user_favorite->companies->occupation}}</span>
                                    </div>
                                </div>
                            </div>
                            <a href="{{route('company.detail',$user_favorite->companies->slug ?? "")}}"
                                    class="btn btn-lg btn-block btn-outline-primary w-25 mt-4 ml-auto mr-auto font-sm">
                                <i class="las la-eye"></i> 詳細を見る
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="d-flex justify-content-center align-items-center">{{$user_favorites->links()}}</div>
        </div>
    @else
        <p class="text-primary text-xl-center font-weight-bold">お気に入りに会社を追加していません</p>
    @endif

@endsection

resources/views/dashboard/left-menu.blade.php
<style>
    p {
        color: #999;
    }

    .link-dashboard,
    .link-dashboard:hover,
    .link-dashboard:focus {
        color: inherit;
        text-decoration: none;
        transition: all 0.3s;
    }

    .navbar {
        padding: 15px 10px;
        background: #fff;
        border: none;
        border-radius: 0;
        margin-bottom: 40px;
        box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
    }

    .navbar-btn {
        box-shadow: none;
        outline: none !important;
        border: none;
    }

    .line {
        width: 100%;
        height: 1px;
        border-bottom: 1px dashed #ddd;
        margin: 40px 0;
    }

    .wrapper {
        display: flex;
        width: 100%;
        align-items: stretch;
    }

    #sidebar {
        min-width: 250px;
        max-width: 250px;
        background: #7386D5;
        color: #fff;
        transition: all 0.3s;
    }

    #sidebar.active {
        margin-left: -250px;
    }

    #sidebar .sidebar-header {
        padding: 20px;
        background: #6d7fcc;
    }

    #sidebar ul.components {
        padding: 20px 0;
        border-bottom: 1px solid #47748b;
    }

    #sidebar ul p {
        color: #fff;
        padding: 10px;
    }

    #sidebar ul li a {
        padding: 10px;
        display: block;
    }

    #sidebar ul li a.link-dashboard:hover {
        color: #7386D5;
        background: #fff;
    }

    #sidebar ul li a.link-dashboard.active{
        color: #7386D5;
        background: #f5f2f2;
    }

    #sidebar ul li.active > .link-dashboard,
    .link-dashboard[aria-expanded="true"] {
        color: #fff;
        background: #6d7fcc;
    }

    .link-dashboard[data-toggle="collapse"] {
        position: relative;
    }

    .dropdown-toggle::after {
        display: block;
        position: absolute;
        top: 50%;
        right: 20px;
        transform: translateY(-50%);
    }

    ul ul .link-dashboard {
        font-size: 0.9em !important;
        padding-left: 30px !important;
        background: #6d7fcc;
    }

    ul.CTAs {
        padding: 20px;
    }

    ul.CTAs .link-dashboard {
        text-align: center;
        font-size: 0.9em !important;
        display: block;
        border-radius: 5px;
        margin-bottom: 5px;
    }

    .link-dashboard .download {
        background: #fff;
        color: #7386D5;
    }

    .link-dashboard.article,
    .link-dashboard.article:hover {
        background: #6d7fcc !important;
        color: #fff !important;
    }

    .title-left-menu{
        padding: 16px 16px 16px 16px;
        color: #FFF;
        font-weight: bold;
        border-bottom: 1px solid #47748b;
        text-align: center;
    }

    #content {
        width: 100%;
        padding: 20px;
        min-height: 100vh;
        transition: all 0.3s;
    }

    @media (max-width: 768px) {
        #sidebar {
            margin-left: -250px;
        }

        #sidebar.active {
            margin-left: 0;
        }

        #sidebarCollapse span {
            display: none;
        }
    }
</style>

<nav id="sidebar">
    <div class="sidebar-header">
        <h5>{{bo_user()->name}}</h5>
    </div>
    <p class="title-left-menu">マイページ</p>
    <ul class="list-unstyled components">
        <li>
            <a href="{{route('user.dashboard')}}" @class([
                'active' => Route::is('user.dashboard'),
                'link-dashboard' => true,
            ])>個人情報</a>
        </li>
        <li>
            <a href="{{route('user.favorite')}}"@class([
                'active' => Route::is('user.favorite'),
                'link-dashboard' => true,
            ])>お気に入り登録した企業</a>
        </li>
        <li>
            <a class="link-dashboard" href="#">企業からのメール</a>
        </li>
        <li>
            <a class="link-dashboard" href="#">スケジュール</a>
        </li>
        <li>
            <a class="link-dashboard" href="#">応募済みの企業</a>
        </li>
    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a class="link-dashboard border-light" href="{{ route('logout') }}" class="article"><i class="las la-sign-out-alt"></i> {{ trans('bo::base.logout') }}</a>
        </li>
    </ul>
</nav>

resources/views/dashboard/main.blade.php
@extends('main')

@section('title', __('Search'))

@section('main')

    <div class="wrapper">
        <!-- Sidebar  -->
        @include('dashboard.left-menu')

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="las la-list"></i>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <span class="nav-link" id="active-left-menu-dashboard"></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <div>
                @yield('main-content')
            </div>

        </div>
    </div>

@endsection

@push('javascript')
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

            $('#active-left-menu-dashboard').text($('#sidebar ul li a.active').text());
        });
    </script>
@endpush

resources/views/dashboard/user.blade.php
@extends('dashboard.main')

@section('title', __('Dashboard User'))

@push('css')
    <style media="screen">
        .backpack-profile-form .required::after {
            content: ' *';
            color: red;
        }
    </style>
@endpush

@section('main-content')

        <div class="row">
            @if (session('success'))
                <div class="col-lg-12">
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                </div>
            @endif

            @if ($errors->count())
                <div class="col-lg-12">
                    <div class="alert alert-danger">
                        <ul class="mb-1">
                            @foreach ($errors->all() as $e)
                                <li>{{ $e }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif

            {{-- UPDATE INFO FORM --}}
            <div class="col-lg-12">
                <form class="form" action="{{ route('account.info.store') }}" method="post">

                    {!! csrf_field() !!}

                    <div class="card padding-10">

                        <div class="card-header">
                            {{ trans('bo::base.update_account_info') }}
                        </div>

                        <div class="card-body backpack-profile-form bold-labels">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    @php
                                        $label = trans('bo::base.name');
                                        $field = 'name';
                                    @endphp
                                    <label class="required">{{ $label }}</label>
                                    <input required class="form-control" type="text" name="{{ $field }}" value="{{ old($field) ? old($field) : $user->$field }}">
                                </div>

                                <div class="col-md-6 form-group">
                                    @php
                                        $label = config('bo.base.authentication_column_name');
                                        $field = bo_authentication_column();
                                    @endphp
                                    <label class="required">{{ $label }}</label>
                                    <input required class="form-control" type="{{ bo_authentication_column()=='email'?'email':'text' }}" name="{{ $field }}" value="{{ old($field) ? old($field) : $user->$field }}">
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="la la-save"></i> {{ trans('bo::base.save') }}</button>
                            <a href="{{ bo_url() }}" class="btn">{{ trans('bo::base.cancel') }}</a>
                        </div>
                    </div>

                </form>
            </div>

            {{-- CHANGE PASSWORD FORM --}}
            <div class="col-lg-12">
                <form class="form" action="{{ route('account.password') }}" method="post">

                    {!! csrf_field() !!}

                    <div class="card padding-10">

                        <div class="card-header">
                            {{ trans('bo::base.change_password') }}
                        </div>

                        <div class="card-body backpack-profile-form bold-labels">
                            <div class="row">
                                <div class="col-md-4 form-group">
                                    @php
                                        $label = trans('bo::base.old_password');
                                        $field = 'old_password';
                                    @endphp
                                    <label class="required">{{ $label }}</label>
                                    <input autocomplete="new-password" required class="form-control" type="password" name="{{ $field }}" id="{{ $field }}" value="">
                                </div>

                                <div class="col-md-4 form-group">
                                    @php
                                        $label = trans('bo::base.new_password');
                                        $field = 'new_password';
                                    @endphp
                                    <label class="required">{{ $label }}</label>
                                    <input autocomplete="new-password" required class="form-control" type="password" name="{{ $field }}" id="{{ $field }}" value="">
                                </div>

                                <div class="col-md-4 form-group">
                                    @php
                                        $label = trans('bo::base.confirm_password');
                                        $field = 'confirm_password';
                                    @endphp
                                    <label class="required">{{ $label }}</label>
                                    <input autocomplete="new-password" required class="form-control" type="password" name="{{ $field }}" id="{{ $field }}" value="">
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="la la-save"></i> {{ trans('bo::base.change_password') }}</button>
                            <a href="{{ bo_url() }}" class="btn">{{ trans('bo::base.cancel') }}</a>
                        </div>

                    </div>

                </form>
            </div>

        </div>

@endsection